# Generated by Django 3.0.7 on 2020-06-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(upload_to='images/')),
                ('img_name', models.CharField(max_length=30)),
                ('img_desc', models.TextField(blank=True)),
                ('img_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleria.Category')),
                ('img_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleria.Location')),
            ],
            options={
                'ordering': ['img_name'],
            },
        ),
    ]
